stevenlovegrove/Pangolin

src/image/image_io.cpp
Added flip capability to exr image saving
=> Added flip capability to exr image saving

include/pangolin/video/drivers/pleora.h, include/pangolin/video/video.h, src/video/drivers/join.cpp, src/video/drivers/pleora.cpp, src/video/drivers/unpack.cpp, src/video/video.cpp, tools/VideoViewer/main.cpp
Added ability to run pleora driver as a separate thread.
Added BufferAwareVideoInterface to allow zero copy dropping of frames from join.
=> Thread pleora

src/video/drivers/openni2.cpp
Signed-off-by: Tanner Schmidt <tws10@cs.washington.edu>
=> bug fix for OpenNI2 driver ignoring depth registration

include/pangolin/compat/locks.h, include/pangolin/video/drivers/thread.h, src/CMakeLists.txt, src/video/drivers/debayer.cpp, src/video/drivers/shift.cpp, src/video/drivers/thread.cpp, src/video/video.cpp
Filter that allows running any of the child as a separate thread.
=> New thread filter

include/pangolin/video/drivers/debayer.h, include/pangolin/video/drivers/join.h, include/pangolin/video/drivers/mirror.h, include/pangolin/video/drivers/pleora.h, include/pangolin/video/drivers/thread.h, include/pangolin/video/drivers/unpack.h, include/pangolin/video/video.h, src/image/image_io.cpp, src/video/drivers/debayer.cpp, src/video/drivers/join.cpp, src/video/drivers/mirror.cpp, src/video/drivers/pleora.cpp, src/video/drivers/thread.cpp, src/video/drivers/unpack.cpp, src/video/video.cpp, tools/VideoViewer/main.cpp
Join always syncs continuously.
Remove threading from Pleora.
Add expected timestamp delta to join.
Debayer, unpack, mirror propagate interfaces and call GrabNext/GrabNewest correctly.
=> Video various cleanups

include/pangolin/display/display_internal.h, src/display/device/display_x11.cpp, src/display/widgets/widgets.cpp, src/gl/glfont.cpp
With these changes, my small sample app on Linux that sits in a loop and
creates/destroys windows works properly. Prior to this change, the first
window would stay open and the app would crash upon exit.
=> Slightly better resource management within a GL context.

include/pangolin/var/var.h
This lets pangolin play nicely with the latest version of Eigen
=> Make cast operator and Get() const

CMakeModules/FindLibRealSense.cmake, include/pangolin/video/drivers/realsense.h, src/CMakeLists.txt, src/config.h.in, src/video/drivers/realsense.cpp, src/video/video.cpp
Support for realsense RGBD sensors via librealsense (added FindLibRealsense.cmake as well to find the library). Tested on my Ubuntu 14.04 with current librealsense https://github.com/IntelRealSense/librealsense.
=> Realsense driver

src/video/drivers/ffmpeg.cpp
Hi,
this PR fixes a compilation problem with the current master branch regarding ffmpeg, see #209. Everybody who is also affected by issue, please test whether this also works for you, thank you.
Kind regards,
Patrick
=> Fixed ffmpeg compilation error on Ubuntu 14.04

src/image/image_io.cpp
Pangolin is currently limited to only load PPM and PGM images but not to save them. This PR adds the missing support.
=> Add support for saving PPM and PGM images

include/pangolin/video/drivers/realsense.h, src/video/drivers/realsense.cpp
I got the conflicting return type as in issue https://github.com/stevenlovegrove/Pangolin/issues/251 but for realsense. The proposed pull request perform the similar operation as in commit proposed in the issue thread (https://github.com/stevenlovegrove/Pangolin/commit/f695ffd9274c6f2f32d6d6d3f0b563307fc988cc).
=> Corrections to realsense driver

CMakeLists.txt
=> Set Pangolin_DIR for tests. Fixes #357, #326, #286.

pyexamples/SimpleVideo.py, src/python/pypangolin/video.cpp
updated Grab() and writeStreams() in src/python/pypangolin/video.cpp 
updated SimpleVideo.py
=> updated pango python binding

pyexamples/SimpleVideo.py, src/python/pypangolin/video.cpp
added wrapper functions for videoPlaybackInterface
=> Pango binding

external/CMakeLists.txt
=> Fix export/install in directories which contain a space

src/image/image_io_exr.cpp
This patch allows to load 1, 3 or 4 channel 32-bit floating point OpenEXR files. So far I tested loading data with 1 and 3 channels.
=> Support 1, 3 and 4 channel OpenEXR files.

CMakeLists.txt, src/CMakeLists.txt
When Pangolin is used in other projects these targets collide
Also fixes https://github.com/stevenlovegrove/Pangolin/issues/355 
TEST: Build on OSX and run samples
=> Use unique uninstall & doc targets

src/display/device/display_wayland.cpp
Just a small set of fixes for the Wayland window interface.
=> Wayland fixes

src/python/pypangolin/display.cpp
Tested locally on Fedora w/ python 3.7
=> added python binding for DestroyWindow

CMakeModules/FindFFMPEG.cmake
This PR adds the paths to find FFMPEG on multiarch systems.
=> Add multiarch paths

include/pangolin/video/drivers/ffmpeg.h, src/video/drivers/ffmpeg.cpp
=> ffmpeg mp4 writing default to not flip frames vertically

.travis.yml
Small fix to add `wayland-protocols` to CI and install apt packages without suggestions and recommendations.
=> add wayland-protocols to CI

src/python/pypangolin/gl.cpp, src/python/pypangolin/gl.hpp, src/python/pypangolin/gl_draw.cpp, src/python/pypangolin/glsl.cpp, src/python/pypangolin/glsl.hpp, src/python/pypangolin/opengl_render_state.cpp, src/python/pypangolin/pypangolin.h, src/python/pypangolin/viewport.cpp
Exposes (some) of the functionality for GLSL programs and frame buffer rendering, and some utilities like drawing frusta and frames of reference.
=> more python bindings for rendering

include/pangolin/gl/gl.hpp
Fixes https://github.com/stevenlovegrove/Pangolin/issues/433
=> Define GlFormatChannels for GL_BGR and GL_BGRA

include/pangolin/display/view.h, src/display/view.cpp, src/handler/handler.cpp
Sorry for creating a new pull request, it's identical with [this one](https://github.com/stevenlovegrove/Pangolin/pull/429).
=> Scroll in LayoutVertical with not shown displays

pyexamples/SimpleDisplay.py, pyexamples/SimplePlot.py, pyexamples/SimpleVideo.py
shebangs for conveniently running scripts as executables and without guessing the required Python version :-)
=> set Python 3 shebang for example scripts

src/video/drivers/openni.cpp
This reverts commit c76e8a09f077a01118523b349986186df3e30aee.
=> Revert "fix switch statement"

README.md
=> Fix build target for docs

.github/workflows/build.yml, CMakeLists.txt
Disable tests by default in the CMake and enable them in the CI.
=> disable tests in default configuration

.github/workflows/build.yml, README.md, scripts/install_prerequisites.sh
Small updates to the install script and documentation.
=> doc and script update

components/pango_image/src/image_io_tiff.cpp, components/pango_image/src/image_io_zstd.cpp, components/pango_opengl/include/pangolin/gl/gl.hpp, components/pango_vars/include/pangolin/var/varvaluegeneric.h
- signed/unsigned comparison
- unsigned is always >= 0
- Intializer list order
- strncpy complains that destination is bound size of 16
=> fix a few warnings.

components/pango_scene/include/pangolin/scene/scenehandler.h
scenehandler fixed for issue https://github.com/stevenlovegrove/Pangolin/issues/784
=> + fix minor issue: scenehandler compile errors - missing template arguments

components/pango_opengl/src/gltext.cpp
=> Fix text renderings in 3D

README.md, scripts/install_prerequisites.sh
Closes https://github.com/stevenlovegrove/Pangolin/issues/736 (this is an old one, but I think having pacman support would be great anyway).
=> Modify install_prerequisites.sh to support pacman (Arch)

.github/workflows/build.yml, .github/workflows/colcon-workspace.yml
Update the macOS runner to test on newer versions.
=> update macOS CI runner

examples/PythonExamples/SimpleDisplay.py
The Python shebang was missing from `SimpleDisplay.py`.
=> add shebang to SimpleDisplay.py

components/pango_core/CMakeLists.txt, components/pango_display/CMakeLists.txt, components/pango_geometry/CMakeLists.txt, components/pango_glgeometry/CMakeLists.txt, components/pango_image/CMakeLists.txt, components/pango_opengl/CMakeLists.txt, components/pango_packetstream/CMakeLists.txt, components/pango_plot/CMakeLists.txt, components/pango_python/CMakeLists.txt, components/pango_scene/CMakeLists.txt, components/pango_tools/CMakeLists.txt, components/pango_vars/CMakeLists.txt, components/pango_video/CMakeLists.txt, components/pango_windowing/CMakeLists.txt, components/tinyobj/CMakeLists.txt
- Add SOVERSION to all SOs
This has only been tested on Linux.
=> Add SONAME Versioning

scripts/install_prerequisites.sh
Avoid reinstalling already up to date packages
=> Improve pacman prerequisites installation
