src/gl/glfont.cpp
The linkage of this symbol doesn't work when building in MSVC since the font is embedded in fonts.c rather than fonts.cpp
=> Fix linkage of AnonymousPro_ttf

include/pangolin/video/drivers/ffmpeg.h, src/video/drivers/ffmpeg.cpp
Some of the old definitions in the code are no longer usable with recent version of ffmpeg (removed by [this commit](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=c10caea2144fefc5e3e80807f301b3bf7a9b2753) on 2015/09/05). This commit should fix it.
Fixes #27
=> FFMPEG: fixed removed libav definitions.

include/pangolin/video/drivers/pleora.h, src/video/drivers/join.cpp, src/video/drivers/pleora.cpp, src/video/video.cpp
Patch that adds GrabNewest to join driver; this allows to deal gracefully (and avoid lag) in cases in which join is not called fast enough.
=> Address join sync lag.

examples/CMakeLists.txt, examples/SharedMemoryVideoWriter/CMakeLists.txt, examples/SharedMemoryVideoWriter/main.cpp, include/pangolin/utils/posix/condition_variable.h, include/pangolin/utils/posix/semaphore.h, include/pangolin/utils/posix/shared_memory_buffer.h, include/pangolin/video/drivers/shared_memory.h, src/CMakeLists.txt, src/utils/posix/condition_variable.cpp, src/utils/posix/semaphore.cpp, src/utils/posix/shared_memory_buffer.cpp, src/video/drivers/shared_memory.cpp, src/video/video.cpp
This PR creates a virtual camera driver that can be driven via POSIX shared memory. A producer creates a shared memory buffer and a condition variable to signal that it is full. A consumer can create the `SharedMemoryVideo` driver and poll via `VideoInterface`
=> Shared memory video driver

include/pangolin/plot/datalog.h
This pointer would be freed multiple times, resulting in memory corruption.
=> Fix memory corruption in DataLog destructor

include/pangolin/utils/params.h, include/pangolin/video/drivers/pleora.h, include/pangolin/video/video.h, src/utils/uri.cpp, src/video/drivers/pleora.cpp, src/video/video.cpp
Updating pleora driver to use generic options directly from command line.
To maintain ordering it was necessary to turn ParamMap into a std::vector.
=> Pleora generic parameters

include/pangolin/utils/params.h, include/pangolin/video/video.h, src/video/drivers/pleora.cpp
Pleora added support for generic command line commands through syntax Command=Execute
Params.h allows repeated commands but Get will always return the last value for the key (command line options are read in left to right order).
=> Command line support for repeated options.

include/pangolin/log/packetstream.h, include/pangolin/utils/file_utils.h, include/pangolin/video/drivers/pango_video.h, src/log/packetstream.cpp, src/utils/file_utils.cpp, src/video/drivers/pango_video.cpp, src/video/drivers/pango_video_output.cpp
These commits make pipe input and output much more robust to applications disappearing on either end. With these changes, I was able to have sample applications start/stop and have them pick right back up where they left off.
The first couple of commits add some infrastructure to be used later. `PacketStreamReader` is refactored a bit next. Then, reader and writer code paths are both made more robust.
`PipeOpen` leaks file descriptors, but closing the file descriptor within `PipeOpen` would cause a reader to believe the pipe was empty and that the writer had disappeared. Instead, the file descriptor is kept open until higher level code can figure out what to do with it. Because `PangoVideoOutput` now opens the file before closing this extra file descriptor, the reader doesn't get …
=> Make pipe video input/output much more robust

include/pangolin/display/device/WinWindow.h
This set of commits makes the following changes:
- Adds a copy constructor for `GlBufferCudaPtr`
- Improves tracking of the current thread's active PangolinGl context
- Adds explicit context sharing which is necessary on Windows because after a context has been used, it is no longer shareable. It's possible to have the creation code path silently fail when sharing is not permitted, but I think this is better.
=> Shared contexts

include/pangolin/gl/gl.hpp, include/pangolin/handler/handler_image.h, src/handler/handler_image.cpp
These changes do two things:
- Use glTexImage2D for texture uploads
- Add a helper to render a texture not captured in GlTexture (since there is no way to construct one from an existing texture resource).
=> Some minor GL related changes

include/pangolin/log/packetstream.h, src/log/packetstream.cpp
Fix for supporting dynamically sized packets in the PacketStream. There was a bug in the ReadCompressedUnsignedInt() function. And the size of the dynamic packet needed to be read from the file as well.
=> PacketStream reader dynamic size

CMakeLists.txt, examples/SharedMemoryVideoWriter/main.cpp, examples/SimpleDisplay/main.cpp, examples/SimpleDisplayImage/main.cpp, examples/SimpleMultiDisplay/main.cpp, examples/SimplePlot/main.cpp, include/pangolin/compat/glutbitmap.h, include/pangolin/python/PyPangoIO.h, include/pangolin/python/PyVar.h, include/pangolin/utils/fix_size_buffer_queue.h, src/console/ConsoleView.cpp, src/display/device/display_x11.cpp, src/display/widgets/widgets.cpp, src/gl/stb_truetype.h, src/handler/handler.cpp, src/log/packetstream.cpp, src/plot/datalog.cpp, src/plot/plotter.cpp, src/python/PyModulePangolin.cpp, src/video/drivers/images.cpp, src/video/drivers/test.cpp, src/video/drivers/v4l.cpp
These commits enable the Wextra flag and fix most warnings related to it.
Despite a warning related to the Py_INCREF macro in src/python/PyModulePangolin.cpp tthat cannot be fixed, Pangolin compiles without any noise. I may missed some warnings since I have not installed all but the most important libraries Pangolin makes use of.
=> Enabled Wextra flag and fixed several warnings

src/CMakeLists.txt
Your latest commit about suppressing the unresolvable python warning does not work for me on Ubuntu 14.04 with GCC 4.8. set_source_files_properties seems to overwrite the flags when invoked twice on the same file. Therefore, only the flags from the last call are used.
In order to fix that, set_source_files_properties should be called for each file once and all flags should be provided for this call. I observed that python/PyInterpreter.cpp does not need the -fno-strict-aliasing flag anymore (no call of Py_INCREF and no warning on my system with Python 2.7), so I removed it.
=> Fixed warning suppression in python module

src/video/drivers/depthsense.cpp, src/video/drivers/openni.cpp
This commit includes two more fixes for unused-parameter warnings. I went through all video drivers and everything should be fine now.
=> Fixed unused-parameter warnings in video drivers

include/pangolin/video/drivers/depthsense.h
Hi,
This PR fixes a typo that was introduced when removing boost dependencies
=> Fix typo in include directives

include/pangolin/gl/glcuda.h, include/pangolin/gl/glpixformat.h, src/image/image_common.cpp
Adding support for "BGRA32" in VideoPixelFormat and GlPixFormat, which is the format for the Kinect2 color stream. 
I'm also unsure of the need for "BGRA24" in line 48 of glpixformat.h, it seems that format is unlikely. "BGRA48" seems similarly unlikely although perhaps plausible. Also, neither appear in the supported formats in image_common.cpp, so they should probably either be added to the one or removed from the other.
Signed-off-by: Tanner Schmidt <tws10@cs.washington.edu>
=> support for BGRA32 VideoPixelFormat

include/pangolin/gl/colour.h
```include/pangolin/gl/colour.h``` makes references to ```floor``` and ```sqrt``` but does not include ```cmath`` for these references to work.
=> Fixed missing cmath include

include/pangolin/platform.h, src/display/display.cpp, src/display/view.cpp, src/image/image_io.cpp
When building with all optional dependencies disabled, some unused parameter warnings occur. This commit fixes that by suppressing them using the defined `PANGOLIN_UNUSED` macro that works for all compilers.
=> Suppressed unused-parameter warnings

include/pangolin/image/image.h, src/video/video_output.cpp
When looking into the logs and messages by Appveyor, there are a couple of warnings emitted. While most of them are related to external libraries like libjpg or caused by an overly picky Visual C++, there are two warnings that should be fixed.
The first commit is related to a warning about an implicit cast of a pointer to `bool`. Although it is not really important, fixing it by a direct check against a null pointer also clarifies the intention of `IsOpen` a bit.
The other commit is more critical since the user might pass a negative row number to an image object and would get a pointer to an illegal memory position. Thanks to the warning about an implicit cast of `size_t` to `int`, this is now fixed.
=> Fixed some Appveyor warnings

include/pangolin/console/ConsoleView.h, include/pangolin/display/device/OsxWindow.h, include/pangolin/display/device/WinWindow.h, include/pangolin/display/device/X11Window.h, include/pangolin/display/display_internal.h, include/pangolin/gl/glcuda.h, include/pangolin/handler/handler_image.h, include/pangolin/platform.h, include/pangolin/python/PyInterpreter.h, include/pangolin/utils/threadedfilebuf.h, include/pangolin/video/drivers/images.h, include/pangolin/video/drivers/pango.h, include/pangolin/video/drivers/pango_video_output.h, include/pangolin/video/video_output.h, include/pangolin/video/video_record_repeat.h, src/display/device/PangolinNSApplication.mm, src/display/device/PangolinNSGLView.mm, src/display/device/display_osx.mm
Because Pangolin now requires C++11, I observed that we can drop the `PANGOLIN_OVERRIDE` macro and use `override` directly as is done by some files already. The other two commits fix some warnings I encountered in the logs of Travis related to the OSX builds.
=> Travis warnings

include/pangolin/video/drivers/openni2.h, include/pangolin/video/drivers/openni_common.h, src/video/drivers/openni2.cpp
added cropping to OpenNI2 driver and added option for turning on fast crop mode.
with this change, a crop of an OpenNI2 stream is taken by adding the symbol '#' to the stream string followed by an ImageRoi of the form X+Y+WxH. the fast cropping mode can be activated with the option 'fastcrop'. for example:
openni2:[img1=depth:640x480@30,img2=rgb:1280x1024@30#320+240+640x480,fastcrop=true,framesync=true]//
=> OpenNI2 cropping

include/pangolin/utils/simple_math.h
The bug is reproduced in win64. The variable 'T_wc' is composed of 12 double's, but `T_wc[12]` is wrote in function `LieSE3from4x4<>()`. Please check the code directly.
B. R.
maxint
=> Fix bug: stack around the variable 'T_wc' was corrupted

src/video/drivers/ffmpeg.cpp
On Mac, it's necessary to add the include for the array template type.
=> Fixing Issue #183 Compilation Problems

examples/SimplePlot/main.cpp, include/pangolin/gl/colour.h, include/pangolin/image/managed_image.h, include/pangolin/image/typed_image.h, include/pangolin/video/drivers/merge.h, src/video/drivers/merge.cpp
I've found these warnings in the Appveyor log. The `size_t -> int` warning might be critical if the user tries to pass negative numbers. The `double -> float` warning is less problematic, but should be fixed too.
=> Fix Appveyor warnings

include/pangolin/video/drivers/realsense.h, src/video/drivers/realsense.cpp
My first pull request in github. Hope its usefull. 
Just fixing a little bug which leads to this compile error:
realsense.h:81:5: error: ‘ImageDim’ does not name a type
ImageDim  dim_;
=> Compile Error Fix

src/CMakeLists.txt, src/display/view.cpp, src/image/image_io.cpp
Hi,
This PR fixes some link errors when `BUILD_PANGOLIN_VIDEO` is turned off.
Kind regards,
Patrick
=> Fixed link errors when video support is disabled

include/pangolin/tools/video_viewer.h, include/pangolin/video/drivers/images.h, include/pangolin/video/drivers/join.h, src/tools/video_viewer.cpp
Add missing export for VideoViewer tool.
Fixes #223.  
There is still a lot of warnings about missing library and `std::` exports.  
I did't change one, because I don't know what do you think about pangolin`s public API.
=> Fix msvc14 shared library build.

include/pangolin/image/image.h
Removed const keyword preventing std::pair from being updated and throwing read-only assignment error
=> Fixed std::pair<T,T> MinMax() function

src/plot/plotter.cpp
Hey @stevenlovegrove , 
First, awesome tool. I have been using it for a couple months now and it's amazing.
I ran into some issues with the Plotter while on Windows 7. 
Namely, when a plotting view is active and the application window is minimized, the entire window hangs and cannot be brought up again. I tracked it down to [src/plot/plotter.cpp#L430](https://github.com/stevenlovegrove/Pangolin/blob/f695ffd9274c6f2f32d6d6d3f0b563307fc988cc/src/plot/plotter.cpp#L430)
When the window is minimized the viewport width/height are set to zero (at least on windows), so the render code never breaks out of that loop.  If you want to double check the issue, the SimplePlot example has this problem.
The proposed solution is simple: only go into the loop if the viewport dimensions are non-zero.
=> fixing plot issue on windows

include/pangolin/video/drivers/openni2.h, src/video/drivers/openni2.cpp
For OpenNI2 driver, prevents setVideoMode when an .oni file uri is given, since that results in an OpenNI2 error. Solution tested for .oni files & on OpenNI device.
=> Solution for #45

include/pangolin/gl/gldraw.h
These commits enable `glDrawAxis` to set the reference frame from `pangolin::OpenGlMatrix`.
=> glDrawAxis with OpenGlMatrix

src/image/image_io.cpp
This commit fixes the PNG export which expects compression levels in the range [0,9] but is called with compression levels in the range [0,100] which causes the exception:
```
libpng error: zlib failed to initialize compressor -- stream error
terminate called after throwing an instance of 'std::runtime_error'
what():  PNG Error: Error during png creation.
```
The issue can be solved by mapping the image quality to compression levels for PNG export.
=> Determine PNG compression level from quality

examples/SimpleDisplay/main.cpp
missing "_"   in SetVarFunctor construction.
Signed-off-by: Markus Murschitz <dreckmarkus@gmail.com>
=> Fixed Core Dump crash, when CTRL+b was pressed caused by typo 

src/image/image_io_exr.cpp
Fixes the missing class definition:
```
Pangolin/src/image/image_io_exr.cpp:35:31: error: invalid use of incomplete type ‘class Imf::IStream’
class StdIStream: public Imf::IStream
```
=> include definition of Imf::IStream

CMakeModules/FindLibRealSense.cmake
In code it's #include <librealsense/rs.hpp> but in CMake the path with subdir librealsense is saved. So if the upper dir is not added by others (/usr/local/include or any non-default path that librealsense was installed in), the compile will fail.
=> Fix librealsense include path finding

include/pangolin/video/drivers/depthsense.h
In the latest master (2fda7e4) the following error is happening: 
```
Pangolin/include/pangolin/video/drivers/depthsense.h:55:98: error: ‘ImageDim’ has not been declared
DepthSenseVideo(DepthSense::Device device, DepthSenseSensorType s1, DepthSenseSensorType s2, ImageDim dim1, ImageDim dim2, unsigned int fps1, unsigned int fps2, const Uri& uri);
```
This PR fixes it.
=> Fix compilation

.travis.yml, include/pangolin/gl/colour.h, src/CMakeLists.txt, src/display/device/display_wayland.cpp, src/display/device/display_x11.cpp, src/display/display.cpp, src/python/pypangolin/colour.cpp
I continued the work of @gapaluec and implemented the window interface for Wayland (https://github.com/stevenlovegrove/Pangolin/issues/236). I am now at the state where I can process all keyboard and mouse input, show the rendered surface and resize the window (including fullscreen via tab).
At the moment, the used window interface (X11 or Wayland) is selected at runtime. If a Wayland server is available (i.e. when running a Wayland compositor), the Wayland interface is selected. If no compositor is available, it falls back to X11. For this reason, the X11 and Wayland windows use the same `scheme` which I called `linux` for now.
This also introduces new dependencies on wayland, xkbcommon and EGL (`sudo apt install libwayland-dev libxkbcommon-dev libegl1-mesa-dev`).
There are some issues …
=> Wayland + EGL support

CMakeLists.txt, appveyor.yml, external/CMakeLists.txt, src/CMakeLists.txt
This PR adds support for modern target-based linking where the include directories are automatically propagated without further commands. The old fashioned way of linking (with `(target_)include_directories`) is still supported for users relying on it.
=> Use target-based include_directories to enable modern CMake usage

src/display/device/display_wayland.cpp
This PR defines the wayland callbacks again if they are supported and used.
Fixes https://github.com/stevenlovegrove/Pangolin/issues/363 and https://github.com/stevenlovegrove/Pangolin/issues/364 but should also silent warnings about unused functions.
=> Fix wayland warnings

.travis.yml, CMakeLists.txt
Fix #356.
I added `libstdc++-5-dev` from the `ubuntu-toolchain-r-test` PPA to make clang work on Linux (looks like the system default for trusty is too old, namely libstdc++-4.8).
The failure of GCC in Linux seems to be from master, but interestingly also fails in a libstdc++-4.8 header it seems.
Note that travis is already on clang-5.0, so no need to set it up manually (as you attempt in https://github.com/stevenlovegrove/Pangolin/commit/b98d8f70ea822de205dada9d2480d471a5fd9f37).
I could add to the README a note for Trusty users that want to use clang to install newer libstdc++ or pass flags to use libc++ is needed. Should I do that?
=> Remove unnecessary stdlib flag, allowing user to override if necessary.

include/pangolin/display/viewport.h, src/display/view.cpp, src/display/viewport.cpp
This PR creates a `GetCamCoordinates` method for the `Viewport` to allow projection with fixed viewport dimensions.
This simplifies the use like in https://github.com/stevenlovegrove/Pangolin/issues/375:
```C++
pangolin::Viewport offscreen_view(0,0,w,h);
offscreen_view.Activate();
offscreen_view.GetCamCoordinates(robot_cam, x, y, double(depth_gl(y,x)), points(y,x)[0], points(y,x)[1], points(y,x)[2]);
```
=> GetCamCoordinates for Viewpoint to allow projection with fixed dimensions

include/pangolin/var/var.h
Without this the min-max values are interpreted as powers of `e`.
The code section is copied from the corresponding `Var` constructor further down.
Tested on macOS.
=> Fix min/max values for Attach with log scale.

examples/CMakeLists.txt, examples/HelloPangolinThreads/CMakeLists.txt, examples/HelloPangolinThreads/main.cpp, include/pangolin/display/device/OsxWindow.h, include/pangolin/display/device/WinWindow.h, include/pangolin/display/device/X11Window.h, include/pangolin/display/display_internal.h, include/pangolin/display/window.h, src/display/device/display_osx.mm, src/display/device/display_wayland.cpp, src/display/device/display_win.cpp, src/display/device/display_x11.cpp, src/display/display.cpp, src/python/pypangolin/window.cpp
This PR contains a subpart of commits from PR https://github.com/stevenlovegrove/Pangolin/pull/389 which deals with context sharing. I am submitting this set of commits since it is already useful for X11+GLX and removes the requirement to rebase these commits on master for maintaining the `x11_egl` branch.
As discussed in https://github.com/stevenlovegrove/Pangolin/pull/395, thread local storage only works for sequentially created threads. I.e. it does not work in the `HelloPangolinThreads` example, where a window is created in the main thread and rendering is done in a separate run thread.
The PR mainly adds a new method `RemoveCurrent` for `WindowInterface`/`PangolinGl` which is supposed to unbind the current context. As shown in the example, it needs to be called at the end of a …
=> RemoveCurrent method for thread context sharing

src/python/pypangolin/video.cpp
This allows to import RGB96F and RGB128F pango files when using the python binding.
=> Added support for RGB96F and RGBA128F in python binding.

src/python/pypangolin/video.cpp
`VideoOutput.WriteStreams` assumes a c-style memory layout of numpy arrays, which was not guaranteed. (It is easy to break this assumption using various numpy methods). Setting the flag `pybind11::array::c_style` ensures that the correct memory layout is used.
=> Ensure c-style memory layout

pyexamples/SimpleVideo.py, src/python/pypangolin/video.cpp
This pull request makes the python binding of `VideoInput` iterable and enables a more pythonic way of running over an input sequence. The according python example is also updated and a minor bug in the example is fixed.
The (broken) python interfaces for the functions `GrabNext` and `GrabNewest` are removed.
=> Pythonic video iterations

src/display/device/display_win.cpp
Initialize the default Windows windows to width/height instead
of 0.
Fixes: https://github.com/stevenlovegrove/Pangolin/issues/367
TEST: Runs the windows samples without having to resize
=> Fix Windows black screen

src/video/stream_encoder_factory.cpp
Instead of using `PANGO_ENSURE`, throw a more descriptive `std::invalid_argument` in case of an unrecognized encoder string.
=> Show a more informative exception, if an unsupported encoder is used.

include/pangolin/scene/interactive.h
This fixes a runtime crash when running with [UndefinedBehaviorSanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) enabled because the Interactive interface was missing a virtual destructor.
=> Fix Pangolin virtual destructor error

src/gl/stb_truetype.h
The old version of stb_truetype.h was causing a crash due to faulty math in its font rasterization code resulting in a divide by zero error caught by the [UndefinedBehaviorSanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html).
=> Update Pangolin stb_truetype.h version

tools/ModelViewer/main.cpp
I noticed that the ModelViewer tool was crashing for some valid OBJ files and only in a release build, with the following message: 
> terminate called after throwing an instance of 'std::invalid_argument'
what():  'Look' and 'up' vectors cannot be parallel when calling ModelViewLookAt.
I could trace this down to a _nan_ in the **view** vector here https://github.com/stevenlovegrove/Pangolin/blob/8cd484a782f4f37a7d5ec61cfcbf453ee5f7a12f/tools/ModelViewer/main.cpp#L119 (even though having solely sensible values when calculating the **view** vector).
It turns out that using the _auto_ keyword in combination with Eigen is known to provoke issues, as described in further detail here: https://eigen.tuxfamily.org/dox/TopicPitfalls.html (see: _C++11 and the auto keyword_)
Replacing _auto_ with …
=> Fix Eigen issue in ModelViewer

src/display/device/display_win.cpp
Window classes and instances store data, like window titles, in the native format implied by which API was used (ASCII or UNICODE). However, that knowledge isn't stored, and it is thus up to the client to use the consistent set of APIs for the stored text data to be interpreted properly.
This explicitly uses the ASCII API versions everywhere so that this functionality works properly if the code is compiled with UNICODE defined.
Even better would be to use UTF-8 encoded strings and translate them to UNICODE in the Win32 API calls, but that would be a more substantial change best done after the pending refactor.
=> Fix window titles when compiling with UNICODE on Windows

examples/HelloPangolinOffscreen/main.cpp
Some OpenGL drivers (e.g. intel) seem to have issues with rendering into a pixel buffer (`EGL_SURFACE_TYPE` set to `EGL_PBUFFER_BIT`).
This PR extends the offscreen rendering example with rendering directly into an FBO without relying on the pixel buffer.
=> offscreen rendering to FBO

src/plot/datalog.cpp
This removes the "not implemented" runtime error and saves a DataLog to csv.
=> Write DataLog to CSV file

src/display/device/PangolinNSApplication.mm, src/display/device/PangolinNSGLView.mm, src/display/device/display_osx.mm
This check was ineffective on macos versions prior to 10.12, since the
constant is not defined there, which caused build failures due to
undefined symbols. By replacing it with the integral value, the
defines should correctly be skipped on macos < 10.12, while behaviour
should remain unchanged on newer versions.
Fixes #327
=> Replace MAC_OS_X_VERSION_10_12 by its value 101200

src/geometry/geometry_obj.cpp
The Pangolin OBJ file loader previously ignored cases in which different indices were used for vertices, normals, and/or textures, which requires reusing the same vertex coordinates with different texture coordinates and/or normals. This change duplicates vertices that are used with different texture and/or normal coordinates and updates the index buffer accordingly.
Furthermore, it seems that the OBJ format assumes textures will be read from bottom to top, causing mismatched texture coordinates. This diff solves this by reading the image and then flipping it vertically, but a further improvement could be to read the inverted image directly.
**Before:**
This simple OBJ cube file reuses the same 8 vertices and 6 normals, which led to bad results with the existing OBJ loader.
**After:**
The …
=> fix for more general OBJ file loading

include/pangolin/video/video_input.h, include/pangolin/video/video_output.h
Hi Steven,
this adds default move constructors for `VideoInput` and `VideoOutput`.
=> Add default move constructor for video_input and video_output

src/python/pypangolin/display.cpp, src/python/pypangolin/params.cpp, src/python/pypangolin/pypangolin.h
I don't see a good reason to split the C++ function `CreateWindowAndBind` into two functions for the python binding (`CreateWindowAndBind` and `CreateWindowAndBindWithParams`), since it is possible to use the same default parameter for the argument `params` in python. To this end, the binding of `Params` simply has to be provided before the binding of `Display`.
This commit removes the python binding `CreateWindowAndBindWithParams` by providing the same functionality with `CreateWindowAndBind` (as in C++).
Further, the python binding of `Params` supports string types now.
Here is an example of how the two changes can be used:
```python3
import pypangolin as pangolin
params = pangolin.Params()
params.Set("scheme", "headless")
pangolin.CreateWindowAndBind("window", 500, 500, params)
```
=> Unify `CreateWindowAndBind` and `CreateWindowAndBindWithParams`

src/geometry/geometry_ply.cpp, src/utils/threadedfilebuf.cpp
1. Fixing an inconsistent usage of 'new []' and 'delete' operators
in utils/threadedfilebuf.cpp.
This inconsistency results in undefined behavior and, potentially,
memory leaks.
2. Removing the explicit 'mpark' namespace specification in
geometry/geometry_ply.cpp.
The `pangolin/geometry/geometry_ply.h -> pangolin/compat/variant.h`
header sequence is supposed to map `get_if` to eiter `std::get_if`
or `mpark::get_if`, depending on the compiler version. This explicit
namespace specification breaks this compatibility behavior.
=> Fixing a couple of compatibility issues

src/geometry/geometry_obj.cpp
Previously, the .obj loader failed completely if any of the textures referenced by an object failed to load for any reason. With this code, it instead issues a warning and discards the texture, allowing downstream applications to determine how to handle references to unloaded textures (and in fact some applications do not need the textures at all and are now no longer blocked from using shapes with textures that can't be loaded).
=> warn and continue on failure to load obj textures

src/python/pypangolin/opengl_render_state.cpp
The rotation about Z-axis was incorrectly calling a rotation about the x-axis
=> Minor change - Fixing typo in pybind module

src/python/pypangolin/gl_draw.cpp
Added python bindings for drawing axis-aligned grids and coordinate axes.
=> additional python bindings for gl drawing helpers

include/pangolin/gl/glinclude.h, include/pangolin/gl/glpangoglu.h, src/gl/glpangoglu.cpp, src/image/image_io_jpg.cpp
Fixes #534 by forwarding the JPEG error to an exception that can be handled by user code. Also includes a fix to print useful OpenGL error messages.
=> Jpeg error handler

src/geometry/geometry_obj.cpp
The buffer for faces should allocate `3 * number of faces` for triangular meshes, but it currently can hold `3 * number of indices`, which is 3x larger than required. 
I tested the model viewer on a couple of meshes and it still works fine (I also verified that it crashes when the size of the buffer would be reduced even further).
=> Allocate memory for the right amount of faces when reading OBJ files.

include/pangolin/var/var.h
This change makes it clear what variable already exists when the runtime error is thrown.
However, I still have the outstanding VideoViewer issue https://github.com/stevenlovegrove/Pangolin/issues/537 which led to this PR:
```
Var with the following name already exists: ui.frame
```
=> var.h print specific Var causing an error

include/pangolin/gl/colour.h, include/pangolin/plot/plotter.h, src/plot/plotter.cpp
Small additional API to reset the colour wheel for a plotter.
This can be useful together with ClearSeries(), when you re-add a set of logs using unspecified color to ensure that they get the same color each time.
=> Plotter: Add API to reset colour wheel.

src/display/device/display_x11.cpp
On some touchscreens, mouse press events are recognized as mouse release events.
Fix this by looking at the event type instead of the state to determine if the mouse is pressed.
This seems to be due to something in X11 getting into a bad state
Physical mouse / touch screen in good state:
Press: ev.xbutton.state=0, ev.xbutton.type=4
Release: ev.xbutton.state=256, ev.xbutton.type=5
Touch screen in bad state:
Press: ev.xbutton.state=256, ev.xbutton.type=4
Release: ev.xbutton.state=256, ev.xbutton.type=5
=> Fix mouse press event on some touchscreens on X11

src/plot/plotter.cpp
Without this, SetView is broken. Since target is not updated, the zooming mechanism will go back to the previous view (or current target view) right after calling SetView.
=> fix Plotter::SetView; not updating target means it zooms back

include/pangolin/geometry/geometry.h, src/display/device/PangolinNSGLView.mm
This PR fixes the following errors that I get when compiling with Xcode 11 on Mac.
Error 1:
```
/Users/vsu/Pangolin/src/display/device/PangolinNSGLView.mm:84:55: error: use of undeclared identifier '_window'
if ( [self wantsBestResolutionOpenGLSurface] && [ _window respondsToSelector:@selector(backingScaleFactor) ] )
^
/Users/vsu/Pangolin/src/display/device/PangolinNSGLView.mm:85:26: error: use of undeclared identifier '_window'
backing_scale = [_window backingScaleFactor];
^
2 errors generated.
```
Error 2:
```
/Users/vsu/Pangolin/include/pangolin/geometry/geometry.h:50:18: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
Element& operator=(const Element&) = default;
^ …
```
=> fix compile with Mac OS Xcode 11

src/CMakeLists.txt
Sets CMake policy CMP0072 to silence warning about unspecified `OpenGL_GL_PREFERENCE` for newer cmake > 3.10.
=> set policy CMP0072 to prefer GLVND for OpenGL_GL_PREFERENCE

include/pangolin/gl/gl.hpp
I noticed I screwed up the indent in d33757da4be5eddbdf1b434b9251477051578fc5 (PR https://github.com/stevenlovegrove/Pangolin/pull/551), sorry. Merge this one to correct or feel free to close without merging.
=> Fix indent in GlFormatChannels

include/pangolin/utils/picojson.h
Without this, if I include 2 libraries that define this macro, I get warnings like
```
warning: '__STDC_FORMAT_MACROS' macro redefined [-Wmacro-redefined]
```
This is on macos 10.15 with AppleClang 11.
See also upstream PR: https://github.com/kazuho/picojson/pull/127
=> fix compiler warning on __STDC_FORMAT_MACROS redef

pyexamples/SimpleDisplay.py, src/python/pypangolin/var.cpp, src/python/pypangolin/var.hpp
Current pypangolin bindings only allow `pangolin::Var<T>` objects to be created with a single parameter of type` T` passed to the constructor. The reason (I assume) is that it is implemented by overriding the Python functionality for setting attributes of an object, which only takes one parameter.
Passing multiple arguments is super useful, as it allows you to change widget types (e.g. button vs checkbox) and set min/max ranges on sliders.
As a way around this without changing the functionality drastically, I created an intermediate Python class called `VarMeta` which serves as a vehicle to pass these additional arguments to the `Var` constructor. Now, a `Var` can be constructed by passing a single object of a supported class (the value), or a 2-element tuple containing the value followed …
=> [pypangolin] allow multiple args to pangolin::Var

include/pangolin/geometry/geometry_ply.h
The PLY loader defines the set of supported PLY property types. Although all possible scalar types [1] are defined and supported (char, uchar, ..., double), there is also an alternative/alias type [2,3] for each of them (int8,uint8, ..., float64) that is not included here. Since many other libraries and tools support both formats, a user might be confused why certain files that silently use one of these alias types will be rejected by Pangolin. Extend the list of property types to fix this issue.
[1] http://paulbourke.net/dataformats/ply/
[2] http://people.math.sc.edu/Burkardt/data/ply/ply.txt
[3] https://en.wikipedia.org/wiki/PLY_(file_format)
=> geometry: Add alternative PLY property types

src/CMakeLists.txt
Recently, a new CMake warning concerning OpenGL has been fixed (see #545). However, the variable `LINUX` is not defined which makes the warning still appear. Use `_LINUX_` instead which is defined in `CMakeModules/SetPlatformVars.cmake` to fix this issue.
=> cmake: Fix Linux platform check

src/CMakeLists.txt
Support for Wayland has been added in #520. However, the new option `DISPLAY_WAYLAND` does not have any effect if the Wayland client has been found. This leads to generation errors when `xkbcommon` is not installed and `DISPLAY_WAYLAND` is set to `OFF` (which is also the default value). Fix the condition to make the option work as intended.
=> cmake: Fix wayland option

package.xml
A small fix in the `package.xml` to be able to release the package to the ROS repo. This also makes the package depend on Python 3 instead of Python 2, assuming that Pangolin is compatible with Python 3.
~~Before going forward with this, is Pangolin compatible with Python 3? In this case, we should probably depend on the newer python version. At the moment the `python-dev` key points to the `python2-dev` package in Ubuntu.~~
=> rename python dependency

components/pango_windowing/CMakeLists.txt
The call to `PangolinRegisterFactory(WindowInterface WaylandWindow)` was outside of the `if(WAYLAND_CLIENT_FOUND)` block, so the `WaylandWindow` factory was registered regardless of if the Wayland development libraries were found. This PR moves the factory registration inside the block.
Fixes #700 .
=> fix: only register 'WaylandWindow' factory when building with Wayland

components/pango_windowing/CMakeLists.txt
- set only a single `PANGO_DEFAULT_WIN_URI`
- set to `x11` only of not build with Wayland
- set to `wayland` if built with Wayland support, so that Wayland will be preferred automatically and fall back to X11
- Fixes #709
=> set only one default win URI handler and prefer Wayland over X11

components/pango_python/src/pypangolin/gl_draw.cpp, components/pango_python/src/pypangolin/image_view.cpp, components/pango_python/src/pypangolin/var.cpp, components/pango_python/src/pypangolin/var.hpp, examples/PythonExamples/SimpleDisplay.py
This PR extends the python interface of pangolin:
* more functions from `gldraw`.
* Support for `uint8_t` and `uint16_t` image types in `ImageView.SetView`.
* Expose `GuiChanged` for variables in python. Similar to C++ version it resets the flag on read.
*  Update python example to showcase `GuiChanged` and `Toggle`.
=> Extend python interface

components/pango_python/src/pypangolin/view.cpp
Fixes `SetDrawFunction` for `View` in python interface by adding `pybind11/functional.h` headers.
=> Small fix for python interface. Fixes SetDrawFunction in View.

.github/workflows/ros_workspace.yml, package.xml
This adds CI for building the `pangolin` package as part of a catkin or colcon workspace. This makes sure that the dependencies are properly resolved by the `package.xml` and that it builds correctly with the default setup.
=> CI for ROS (catkin/colcon) workspaces

components/pango_image/src/image_io_packed12bit.cpp
https://en.cppreference.com/w/cpp/algorithm/min
The image component fails to build on win 10 using cmake to generate a VS2019 solution without including algorithm.
=> added missing include for std::min

components/pango_core/include/pangolin/utils/range.h
Basically float::max cast to int is too big for that type and it gets sad. Even worse, float doesn't have precision to store even close to int max, meaning you can't just do a std::min() trick to clamp the value.
=> ASAN fix for range

components/pango_python/CMakeLists.txt, components/pango_python/src/pypangolin/glfont.cpp, components/pango_python/src/pypangolin/glfont.hpp, components/pango_python/src/pypangolin/gltext.cpp, components/pango_python/src/pypangolin/gltext.hpp, components/pango_python/src/pypangolin/pypangolin.h, components/pango_python/src/pypangolin/var.cpp, components/pango_python/src/pypangolin/var.hpp
This PR adds GlFont and GlText to python interface and adds small improvements to python variable interface (allows changing meta information for the existing variables).
=> Add GlFont and GlText to python interface.

components/pango_context/src/gl_drawable/gl_drawn_checker.cpp, components/pango_context/src/gl_drawable/gl_drawn_image.cpp, components/pango_context/src/gl_drawable/gl_drawn_plot_background.cpp, components/pango_context/src/gl_drawable/gl_drawn_primitives.cpp, components/pango_context/src/gl_drawable/gl_drawn_solids.cpp, components/pango_context/src/gl_drawable/gl_drawn_text.cpp, components/pango_context/src/gl_layer/gl_widget_layer.h, components/pango_opengl/include/pangolin/gl/glsl_program.h, components/pango_opengl/include/pangolin/gl/uniform.h, components/pango_opengl/src/glsl_preprocessor.cpp, components/pango_opengl/src/glsl_program.cpp, examples/15.reload-example.cpp, examples/6.overlay.cpp, examples/CMakeLists.txt
`GLUniform`s must now be associated with a `GlSlProgram`. 
The `GlSlProgram` will signal associated uniforms when it has been unlinked, so that uniforms can reinitialize themselves.
=> Support shader reload

.github/workflows/build.yml, components/pango_context/src/context.cpp, components/pango_context/src/gl_drawable/gl_drawn_image.cpp, components/pango_context/src/gl_drawable/gl_drawn_primitives.cpp, components/pango_context/src/make_drawable.cpp, components/pango_image/src/image_io_jpg.cpp, components/pango_image/src/image_io_lz4.cpp, components/pango_image/src/image_io_packed12bit.cpp, components/pango_image/src/image_io_png.cpp, components/pango_image/src/image_io_ppm.cpp, components/pango_image/src/image_io_raw.cpp, components/pango_image/src/image_io_tga.cpp, components/pango_image/src/image_io_tiff.cpp, components/pango_image/src/image_io_zstd.cpp, components/pango_opengl/include/pangolin/gl/gl.hpp, components/pango_opengl/include/pangolin/gl/gl_type_info.h, components/pango_opengl/include/pangolin/gl/glpixformat.h, components/pango_opengl/src/gl_device_buffer.cpp, components/pango_opengl/src/gl_device_texture.cpp, components/pango_opengl/src/gl_vao.cpp, components/pango_render/include/pangolin/render/device_buffer.h, components/pango_render/include/pangolin/render/shared_data_package.h, components/pango_video/include/pangolin/video/stream_info.h, components/pango_video/include/pangolin/video/video_interface.h, components/pango_video/src/drivers/ffmpeg.cpp, components/pango_video/src/drivers/images.cpp, components/pango_video/src/drivers/split.cpp, components/pango_video/src/drivers/test.cpp, components/pango_video/src/drivers/transform.cpp, components/pango_video/src/video_output.cpp
I believe the issue with the current implementation is that when indices are specified as a `std::vector<Eigen::Matrix<uint32_t, 3, 1>>`, we run into Eigen alignment issues, i.e. http://eigen.tuxfamily.org/dox-devel/group__TopicFixedSizeVectorizable.html.
I'm not sure what deeper fixes might be necessary to prevent, or fix that usage in the API, but this is a solution for the Icosphere at least; indices are specified as `std::vector<unsigned int>`.
before and after, white icosphere with 4 subdivisions next to default cube:
=> Fix Icosphere

components/pango_display/include/pangolin/handler/handler_image.h, components/pango_display/src/handler_image.cpp
This adds methods to rotate the texture before display in handler_image. Rotation are multiple of 90degrees and can be set by using the `SetThetaQuarterTurn` method.
This changes takes care of making the mouse interaction consistent with the rotation for instance when selecting.
The user should call "glSetModelView" before rendering opengl primitive in the original pixel grid. The function will apply the correction rotation.
Test:
As example, here is a random image draw with the four possible orientations. We draw a white line between pixel (0,0) and (1,1).
With every chosen rotation, the line is correctly displayed.
Code snippet for testing:
```c++
#include <limits>
#include <iostream>
#include <pangolin/display/display.h>
#include <pangolin/display/view.h>
#include …
```
=> Add image rotation option to handler_image

components/pango_packetstream/include/pangolin/log/packetstream_tags.h
- Fedora38 is using g++ (GCC) 13.1.1 and it was complaining about a missing definition error:
```
‘uint32_t’ does not name a type
7 | using PangoTagType = uint32_t;
```
We are fixing it here.
=> [Build] Fix for Fedora38 and modern G++

components/pango_context/src/context.cpp, components/pango_vars/include/pangolin/var/varextra.h
Fixes a linker error 
```
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/deque.tcc:770: multiple definition of pangolin::checkReset();
```
CI was failing due to pre-commit format check; I pushed a fix for that to this PR as well.
=> Add inline to varextra's checkReset()

components/pango_image/src/image_io.cpp, components/pango_image/src/image_io_tiff.cpp
Extends our limited support for TIFF file IO with a `SaveTiff` function
=> Add support for saving TIFF files

.github/workflows/ros_workspace.yml, components/pango_windowing/src/display_wayland.cpp, package.xml
This fixes an issue in the Wayland windowing when decorations are created multiple times without first destroying them. Also, parts of the CI pipeline used outdated actions which are updated with this PR.
=> fix wayland subsurface

package.xml
This adds the Wayland dependencies to the `package.xml` to enable the automatic installation of those dependencies via rosdep and for bloom.
=> Wayland compile and runtime dependencies

.github/workflows/build.yml, CMakeLists.txt, README.md, package.xml, scripts/install_prerequisites.sh
The tests have effectively been disabled in the CI as Catch2 was not installed on Ubuntu and Windows and macOS installed a newer version that CMake would ignore to use. This PR installs Catch2 on Ubuntu 22.04 via the package manager and activates the test for Ubuntu on the CI. For Windows and macOS, Catch2 v3 has to be used and for this, the tests have to be upgraded.
Fixes #847.
=> enabled tests on CI

.github/workflows/build.yml, CMakeLists.txt, components/pango_core/CMakeLists.txt, components/pango_core/include/pangolin/platform.h, components/pango_core/src/threadedfilebuf.cpp, components/pango_display/CMakeLists.txt, components/pango_geometry/src/geometry_obj.cpp, components/pango_packetstream/include/pangolin/log/playback_session.h, components/pango_video/src/drivers/uvc_mediafoundation.cpp
This adds build configurations for testing shared and static builds (`BUILD_SHARED_LIBS` `ON` or `OFF`) for all targets in the CI.
The most notable change here is that I had to remove the export header generation via `GenerateExportHeader` and export all symbols on Windows via `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`. Without this, it is not possible to build a shared Pangolin library as a lot of symbols cannot be resolved with the MSVC compiler.
I am not familiar with development with the MSVC compiler on windows. But I guess the proper solution would be to properly export those symbols by adding `PANGOLIN_EXPORT` to them.
LNK2019 errors:
```
pixel_format.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl pangolin::PixelFormat::PixelFormat(struct …
```
=> enable shared/static builds

components/pango_packetstream/include/pangolin/log/packetstream_tags.h
- error: ‘uint32_t’ does not name a type in packetstream_tags.h
```
[2/113] /usr/bin/g++ -Dpangolin_EXPORTS -I/builddir/build/BUILD/Pangolin-86eb4975fc4fc8b5d92148c2e370045ae9bf9f5d/include -I/builddir/build/BUILD/Pangolin-86eb4975fc4fc8b5d92148c2e370045ae9bf9f5d/redhat-linux-build/src/include -Wall -Wno-error=deprecated-declarations -Wall -Wextra -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DNDEBUG …
```
=> Fix packetstream_tags Build On gnu++14

.github/workflows/build.yml
This switches to the newer macOS 14 runner on the arm64 platform.
=> update macOS on CI

.github/workflows/build.yml, components/pango_python/CMakeLists.txt
Install the built wheel file in the CI to test dependency issues.
I am also removing the dependency on `PyOpenGL-accelerate` due to the Cython compilation errors with Ubuntu 24.04 onwards (https://github.com/stevenlovegrove/Pangolin/issues/947#issuecomment-2325220668).
Fixes https://github.com/stevenlovegrove/Pangolin/issues/947.
=> test wheel file installation

.github/workflows/bloom.yml, package.xml
Test bloom package generation to make sure that all dependencies are properly defined. We cannot bloom on 20.04 as the test dependency `catch2` is unavailable.
=> test blooming of Debian packages

.github/workflows/build.yml, CMakeLists.txt, cmake/MakePythonWheel.cmake, components/pango_python/CMakeLists.txt, scripts/install_prerequisites.sh
Previously, an invalid wheel file is created when `setuptools` is not available. This can be difficult for users to debug.
Fix this by adding an explicit check for the `setuptools` module and fail when it is not available. Additionally, provide some information about the module search paths for debugging.
=> fix wheel name

.github/workflows/build.yml, cmake/MakePythonWheel.cmake
Even with `setuptools` installed, the `bdist_wheel` snippet could still silently fail with an empty wheel filename. Fix this by showing the error and checking the exit code. Also, test for `bdist_wheel` and inform the user.
Fixes #959.
=> show errors and check exit code for wheel filename formatting

README.md
The README did not get updated after the changes introduced by https://github.com/stevenlovegrove/Pangolin/pull/958 (the Python3_EXECUTABLE variable is now used instead of Pyhon_EXECUTABLE).
=> Fix cmake Python executable doc reference

.github/workflows/build.yml
Based on https://github.com/stevenlovegrove/Pangolin/pull/969, this uploads the wheel file, that is built inside the CI, to the release page once a tag is pushed.
The wheel file only includes the Pangolin libraries and not any of the dependencies. Hence, users will still have to install dependencies manually via:
```sh
./scripts/install_prerequisites.sh all
```
Fixes #925, Fixes #968
=> release wheel file

.github/workflows/colcon-workspace.yml, CMakeLists.txt, components/pango_python/CMakeLists.txt, components/tinyobj/include/tinyobj/tiny_obj_loader.h
This fixes an `maybe-uninitialized` warning/error in `struct face_t` that is reported with g++ 14.
Fixes https://github.com/stevenlovegrove/Pangolin/issues/975.
=> manage "uninitialized" warnings
